# Generated by Django 5.1 on 2026-04-29 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('matricula', models.CharField(max_length=50, unique=True, verbose_name='Matrícula')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Servidor',
                'verbose_name_plural': 'Servidores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Setor')),
                ('localizacao', models.CharField(max_length=300, verbose_name='Localização')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300, verbose_name='Nome do Item')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='patrimonios/fotos/', verbose_name='Foto')),
                ('numero_patrimonio', models.CharField(max_length=100, unique=True, verbose_name='Número de Patrimônio')),
                ('qrcode_img', models.ImageField(blank=True, null=True, upload_to='patrimonios/qrcodes/', verbose_name='QR Code')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('servidor_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrimonios', to='core.servidor', verbose_name='Servidor Responsável')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrimonios', to='core.setor', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Patrimônio',
                'verbose_name_plural': 'Patrimônios',
                'ordering': ['numero_patrimonio'],
            },
        ),
        migrations.AddField(
            model_name='servidor',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servidores', to='core.setor', verbose_name='Setor'),
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('confirmacao', 'Confirmação de Local'), ('transferencia', 'Transferência')], max_length=20, verbose_name='Tipo')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('patrimonio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='core.patrimonio', verbose_name='Patrimônio')),
                ('servidor_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='core.servidor', verbose_name='Servidor')),
                ('setor_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_destino', to='core.setor', verbose_name='Setor de Destino')),
                ('setor_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_origem', to='core.setor', verbose_name='Setor de Origem')),
            ],
            options={
                'verbose_name': 'Registro de Auditoria',
                'verbose_name_plural': 'Registros de Auditoria',
                'ordering': ['-registrado_em'],
            },
        ),
    ]
