# Generated by Django 5.1 on 2026-05-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrimonio',
            name='descartado',
            field=models.BooleanField(default=False, verbose_name='Descartado'),
        ),
        migrations.AlterField(
            model_name='registroauditoria',
            name='tipo',
            field=models.CharField(choices=[('confirmacao', 'Confirmação de Local'), ('transferencia', 'Transferência'), ('descarte', 'Descarte')], max_length=20, verbose_name='Tipo'),
        ),
    ]
